import flask
import nltk
import json
import string
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords
from flask import request, jsonify
import difflib


class CustomEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, Result):
            return {"value": obj.value, "percentage": obj.percentage}
        # Let the base class handle the problem.
        return json.JSONEncoder.default(self, obj)


class Result:
    def __init__(self, value, percentage):
        self.value = value
        self.percentage = percentage


app = flask.Flask(__name__)
app.config["DEBUG"] = True
app.json_encoder = CustomEncoder

# nltk.download('stopwords')
stopwords = stopwords.words('english')


def clean_string(text):
    text = ''.join([word for word in text if word not in string.punctuation])
    text = text.lower()
    text = ' '.join([word for word in text.split() if word not in stopwords])

    return text


def cosine_sim_vectors(vec1, vec2):
    vec1 = vec1.reshape(1, -1)
    vec2 = vec2.reshape(1, -1)

    return cosine_similarity(vec1, vec2)[0][0]


def get_similarity_percentage(str1, str2):
    sentences = [
        str1,
        str2
    ]

    cleaned = list(map(clean_string, sentences))
    vectorizer = CountVectorizer().fit_transform(cleaned)
    vectors = vectorizer.toarray()

    percentage = cosine_sim_vectors(vectors[0], vectors[1])
    return percentage


@app.route('/test', methods=['GET'])
def test():
    return "<h1>FOR TEST PURPOSE</h1><p>Ignore this...</p>"


@app.route('/similarity', methods=['POST'])
def similarity():
    data = request.get_json()
    input = data.get('input', '')
    strings = data.get('strings', '')

    results = []

    for x in strings:
        results.append(Result(x, get_similarity_percentage(input, x)))

    results.sort(key=lambda x: x.percentage, reverse=True)

    return jsonify({"input": input, "strings": results})


@app.route('/autocorrect', methods=['POST'])
def autocorrect():
    # settings
    forbidden_words_default = []
    forbidden_distilleries_defaults = []
    word_size = 6
    cutoff = 0.75
    search_field = [
        "w.l. weller",
        "aberlour",
        "eigashima",
        "kavalan",
        "hibiki",
        "old rip van winkle",
        "smögen",
        "glen garioch",
        "irish whiskey to delete",
        "michter",
        "glen grant",
        "blanton's",
        "royal lochnagar",
        "Big Peat",
        "redbreast",
        "ardgowan",
        "blair athol",
        "jim beam",
        "hazelburn",
        "longrow",
        "glen elgin",
        "compass box",
        "haig's",
        "spirit of yorkshire",
        "buchanan's",
        "bell's",
        "j & b",
        "famous grouse",
        "ardnahoe",
        "ben wyvis",
        "old fitzgerald",
        "breuckelen",
        "four roses",
        "bivrost",
        "north british",
        "booker's",
        "kanosuke",
        "miyagikyo",
        "cardrona",
        "mackmyra",
        "milk & honey",
        "lindores abbey",
        "finlaggan",
        "gerston & auchnagie",
        "shinobu",
        "colonel e.h. taylor",
        "nantou",
        "john power & son",
        "strathearn",
        "evan williams",
        "kaiyo",
        "annandale",
        "macallan",
        "hibiki suntory",
        "willett",
        "dalmore",
        "karuizawa",
        "mars shinshu",
        "springbank",
        "lagavulin",
        "fettercairn",
        "talisker",
        "1779",
        "yoichi",
        "beam suntory",
        "chichibu",
        "nikka",
        "benromach",
        "wild turkey",
        "ardbeg",
        "teaninich",
        "glonfarcias",
        "carsebridge",
        "hakushu",
        "glenfiddich",
        "convalmore",
        "glenmorangie",
        "midleton",
        "laphroaig",
        "linkwood",
        "rosebank",
        "glen ord",
        "strathisla",
        "bimber",
        "beriach",
        "amrut",
        "glendronach",
        "bunnahabhain",
        "whyte & mackay",
        "bruichladdich",
        "heaven hill",
        "glenrothes",
        "high west",
        "nevada h&c",
        "hillside",
        "coleburn",
        "shizuoka",
        "old pulteney",
        "old forester",
        "glen mhor",
        "jameson",
        "loch lomond",
        "kilkerran",
        "knockdhu",
        "daftmill",
        "dalwhinnie",
        "balvenie",
        "caol ila",
        "littlemill",
        "inchgower",
        "caledonian",
        "dallas dhu",
        "glen keith",
        "caperdonich",
        "mosstowie",
        "imperial",
        "garrison brothers",
        "sullivans cove",
        "teeling",
        "glen albyn",
        "tomintoul",
        "pittyvaich",
        "kentucky owl",
        "inverleven",
        "strathclyde",
        "garnheath",
        "ardnamurchan",
        "tamdhu",
        "balblair",
        "scapa",
        "north of scotland",
        "cragganmore",
        "jack daniels",
        "tomatin",
        "suntory whisky",
        "raasay",
        "dailuaine",
        "glenglassaugh",
        "port dundas",
        "lochside",
        "wolfburn",
        "glenlossie",
        "chita",
        "bushmills",
        "invergordon",
        "tormore",
        "clynelish",
        "glenallachie",
        "brown forman",
        "ambler",
        "glen scotia",
        "yamazakura",
        "orphan barrel",
        "barrell craft",
        "royal brackla",
        "edradour",
        "limestone branch",
        "ledaig",
        "johnnie walker",
        "tamnavulin",
        "cambus",
        "glenkinchie",
        "glen spey",
        "deanston",
        "ben nevis",
        "glengoyne",
        "torabhaig",
        "glen moray",
        "kilchoman",
        "glenturret",
        "speyburn",
        "glencadam",
        "kininvie",
        "benrinnes",
        "dewars blending",
        "waterford",
        "whistlepig",
        "westland",
        "balcones",
        "nelsons green brier",
        "cardhu",
        "mclain kyne",
        "balmenach",
        "lakes",
        "penderyn",
        "jura",
        "cutwater",
        "akkeshi",
        "oban",
        "nc'nean",
        "tullamore",
        "st george",
        "barton 1792",
        "eden mill",
        "kingsbarns",
        "auchroisk",
        "braeval",
        "auchentoshan",
        "grants",
        "tuthilltown spirits",
        "john haig",
        "mannochmore",
        "tullibardine",
        "copper rivet",
        "aberfeldy",
        "stronachie",
        "glenburgie",
        "white horse123",
        "hanyu",
        "kawasaki",
        "glendullan",
        "lux row",
        "aultmore",
        "new riff",
        "glenury",
        "magdalene",
        "millburn",
        "antiquary",
        "bardstown",
        "old carter",
        "macduff",
        "one eight",
        "western spirits",
        "boone",
        "cotswolds",
        "louisville",
        "jos a magnus",
        "proof wood ventures",
        "st augustine",
        "maker's mark",
        "strathmill",
        "ardmore",
        "bourbon 30",
        "filibuster",
        "smith bowman",
        "backbone",
        "glen flagler",
        "dalmunach",
        "woodford reserve",
        "finger lakes",
        "hiram walker",
        "the vintage malt",
        "high coast",
        "kinclaith",
        "glenlochy",
        "stitzel",
        "dornoch",
        "glenugie",
        "glencraig",
        "ailsa bay",
        "breckenridge",
        "schenley",
        "chugoku jozo",
        "starward new world",
        "dads hat",
        "catskill",
        "cutty sark",
        "ranger creek",
        "boston harbor",
        "fremont mischief",
        "glenmore",
        "ladyburn",
        "crown royal",
        "cooley",
        "allt a bhainne",
        "prichards",
        "outlaw rum",
        "buffalo trace",
        "lawrenceburg",
        "kentucky bourbon distillers",
        "tobermory",
        "gibson canadian",
        "bow street",
        "royal irish",
        "jones road",
        "old grand dad",
        "john's lane",
        "tullamore dew",
        "coleraine",
        "fuji gotemba",
        "hill's liquere",
        "killyloch",
        "arizona",
        "tesetice",
        "james e. pepper",
        "anchor",
        "willowbank",
        "charles medley",
        "blaue maus",
        "kagoshima",
        "potter distilling",
        "brora",
        "cascade hollow",
        "glenora",
        "sonnenscheiner",
        "shinshu mars",
        "slyrs",
        "glen kella",
        "highwood",
        "hollen",
        "humbel",
        "zürcher",
        "nishinomiya",
        "rugenbräu",
        "glann ar mor",
        "panimoravintola beer hunter's",
        "us heit",
        "teerenpeli",
        "bernheim",
        "burgdorfer",
        "chicken hill",
        "cradle mountain",
        "mosterei",
        "gasthof hirsch",
        "hercynian",
        "lark",
        "samuel smith",
        "telser",
        "belgian owl",
        "willy macheiner",
        "warenghem",
        "stokerij de molenberg",
        "hagen rühli",
        "loch ewe",
        "meyer",
        "zuidam",
        "vallei distilleerderij",
        "bieri bauernhof",
        "duvel moortgat",
        "birkenhof",
        "glen els",
        "lüthy",
        "macardo",
        "mavela",
        "locher",
        "stokerij de onrust",
        "triple eight",
        "vingården lille gadegård",
        "whisky castle",
        "abhainn dearg",
        "james sedgwick",
        "rothaus",
        "walter seeger",
        "monstein",
        "braunstein",
        "schwab",
        "liebl",
        "crianza",
        "edgefield",
        "j et m lehmann",
        "forty creek",
        "graanstokerij",
        "kümin weinbau",
        "great southern",
        "clear creek",
        "old raven",
        "la rouget de l'isle",
        "southern grain",
        "slijterij",
        "höhler",
        "eigashima shuzo",
        "catoctin creek",
        "des menhirs",
        "eifel",
        "kampen",
        "fary lochan",
        "haas",
        "pradlo",
        "kilbeggan",
        "craft distillers",
        "wannborga",
        "rock town",
        "roughstock",
        "southern coast",
        "sperbers",
        "langatun",
        "thirteenth colony distilleries",
        "a. smith bowman",
        "ziegler",
        "altstadthof",
        "big bottom",
        "box Destilleri sweden",
        "steinhauser",
        "mississippi river",
        "dakota spirits",
        "delaware phoenix",
        "diedenacker",
        "drexler",
        "few spirits",
        "healeys",
        "hven",
        "braugasthof",
        "new holland",
        "old hobart",
        "spreewald",
        "smooth ambler spirits",
        "sonnenbräu",
        "stauning",
        "surselva bräu",
        "gruel",
        "avadis",
        "bertrand",
        "vielanker brauhaus",
        "weingut mößlein",
        "lebe &geniesse",
        "falken",
        "oregon spirit",
        "waldviertler roggenhof",
        "domaine des hautes glaces",
        "senft",
        "finch",
        "henrich",
        "schlitzer korn",
        "hillrock estate",
        "forschungs",
        "nyborg",
        "kinzig",
        "radermacher",
        "liber",
        "z'graggen",
        "lost spirits",
        "corby spirit",
        "meissener",
        "monde shuzou",
        "aare bier",
        "old world spirits",
        "john distilleries",
        "mönchguter",
        "preussische",
        "qvänum mat",
        "roser",
        "edelbrandwein",
        "sons of liberty",
        "still waters",
        "starward",
        "stoaninger",
        "stranahan's colorado",
        "timboon railway shed",
        "wädi",
        "copper fox",
        "whistling andy",
        "widow jane",
        "wyoming",
        "adnams",
        "aichinger",
        "alberta",
        "hepp",
        "cooperstown",
        "belgrove",
        "de monsieur balthazar",
        "molen",
        "heritage",
        "english spirit",
        "joh. b. geuting",
        "arcus",
        "grythyttan",
        "gute",
        "longhorn",
        "marder distillery",
        "märkische",
        "mosswood distillers",
        "mykulynetsky brovar",
        "nestville",
        "nordisk brænderi",
        "old pogue",
        "old sandhill",
        "öufi brauerei",
        "panimoravintola koulu",
        "praskoveya",
        "druffel",
        "reservoir",
        "rogner",
        "stokerij sculte",
        "spezialitätenbrauerei eckart",
        "edelobst",
        "egnach",
        "corsair",
        "weidenauer",
        "woodinville",
        "woodstone creek",
        "t koelschip",
        "sonoma county",
        "radico khaitan",
        "alpenwhisky",
        "amador",
        "wave distil",
        "uerige",
        "hinricus noyte's spirituosen",
        "békési manufaktura",
        "caldera",
        "camp 1805",
        "york brewery",
        "charbay",
        "whipper snapper",
        "wollbrink",
        "dürr edelbranntweine",
        "dry fly",
        "feisty spirits",
        "brunschwiler",
        "gerhard büchner",
        "glendalough",
        "glina whisky",
        "r. jelìnek",
        "rittmeister",
        "guglhof",
        "hellyers",
        "etter",
        "last mountain",
        "mück",
        "okanagan spirits",
        "kauzen bräu",
        "thomas sippel",
        "patrick breindl",
        "puni",
        "reisetbauer",
        "scriptor",
        "old gamundia whisky",
        "stöfflbräu",
        "steinwälder",
        "dolleruper",
        "bull run",
        "london distillery",
        "the vogel",
        "thomson whisky new zealand ltd",
        "tom's foolery",
        "kiwi spirit",
        "wecklein",
        "alambik",
        "wilderen",
        "günter busch",
        "anno 1940",
        "laws whiskey house",
        "agárdi pálinkafőzde",
        "alley 6",
        "alt enderle",
        "archie rose",
        "agder",
        "de bercloux",
        "black dirt",
        "black gate",
        "stein",
        "blackwater",
        "brenne",
        "broad branch",
        "lake george",
        "victoria distillers",
        "cut spike",
        "bruckners erz bräu",
        "bellerhof",
        "IJsvogel",
        "deheck",
        "hamilton distillers",
        "burger",
        "dietrich",
        "dillon's",
        "dirker",
        "eaglesburn",
        "kalkwijck",
        "cornelius pass roadhouse",
        "det norske",
        "nordik",
        "ergaster",
        "eimverk",
        "blaum",
        "gemenc",
        "george washington's",
        "gerlachus",
        "seetal",
        "authentic seacoast",
        "the helsinki",
        "horstman",
        "tin shed",
        "journeyman",
        "klein duimpje",
        "z.kozuba i synowie",
        "friedrich düll",
        "kymsee",
        "kyrö",
        "donner peltier",
        "gilbert holl",
        "las vegas",
        "lobangernich",
        "brûlerie du revermont",
        "mgp",
        "moutard",
        "lanz",
        "yeti",
        "gerhard wagner",
        "kentucky peerless",
        "pemberton",
        "pfanner",
        "highglen",
        "rebecca creek",
        "bischof",
        "alde gott",
        "great lakes",
        "norrtelje",
        "ralf hauer",
        "schwane",
        "saxa vord",
        "spirit hound",
        "vikre",
        "wakatsuru saburomaru",
        "the grove experience",
        "number nine",
        "west cork distillers",
        "northoff",
        "niederrhein",
        "sauerländer",
        "trolden",
        "valamo monastery",
        "birgitta",
        "castan",
        "franz kostenzer",
        "sasanokawa shuzo",
        "zweiger",
        "twin valley",
        "black button",
        "wood hat spirits",
        "brænderiet limfjorden",
        "cleveland",
        "copperworks",
        "corowa",
        "dà mhìle",
        "mountain laurel",
        "drentsche schans",
        "georges lacroix",
        "preiser",
        "eiger",
        "muller lemmer",
        "psenner",
        "grallet",
        "to tårn bryggeri as",
        "peloni",
        "golan heights",
        "sperling silver",
        "weingut etl",
        "habbel's",
        "ironroot republic",
        "gotland",
        "henry farms",
        "koval",
        "kemper",
        "pirlot stokerij",
        "keuris",
        "kings county",
        "alpirsbacher",
        "m&h",
        "shene estate",
        "mad river",
        "mahrs bräu",
        "tsunuki",
        "mchenry",
        "missouri spirits",
        "moon harbour",
        "nagahama",
        "north of 7",
        "miyashita sake brewery",
        "diesdorfer",
        "peter affenzeller",
        "popcorn sutton",
        "rabbit hole",
        "tweekoppige",
        "säntisblick",
        "neuenburg",
        "shelter point",
        "fein simon's",
        "enghaven",
        "st. patrick's",
        "stark spirits",
        "starlight",
        "stone barn brandyworks",
        "spreewood",
        "dublin liberties",
        "exeter",
        "matsui shuzo",
        "asheville",
        "tipperary boutique",
        "toronto",
        "turv exloo",
        "yukon brewing",
        "kaltenthaler",
        "virginia",
        "wieser",
        "feiner kappler",
        "workshops",
        "wright & brown",
        "yellow rose",
        "sempione",
        "stadsbrouwerij de hemel",
        "asaka",
        "asw",
        "united group",
        "badmils black",
        "de biercée",
        "boldizar",
        "bosch edelbrand",
        "braeckman",
        "brehmer",
        "arnsteiner",
        "chattanooga",
        "clonakilty",
        "conecuh ridge",
        "southern grace",
        "gimli",
        "höck",
        "dancing cows",
        "pennington",
        "deerhammer",
        "ehringhausen",
        "scissortail",
        "spielberger",
        "augustus rex",
        "eau claire",
        "thuisbrunner elch bräu",
        "borchert",
        "fannys bay",
        "fleurieu",
        "hessische spezialitätenbrennerei",
        "fukano",
        "gammelstilla",
        "mühle4",
        "gölles",
        "griffo",
        "acha",
        "stonecutter",
        "ironclad",
        "isfjord",
        "browar ciechan",
        "harald keckeis",
        "hart family brewers",
        "helios",
        "la piautre",
        "liberty call",
        "central city",
        "lucky bastard",
        "cali",
        "geiger",
        "mcdowell's",
        "fesslermill",
        "mosgaard whisky",
        "naguelann",
        "nant",
        "new york distilling",
        "old kempton",
        "svach",
        "rabel",
        "pearse lyons",
        "pelter",
        "pfau brennerei",
        "cave de la crausaz",
        "still 630",
        "chankaska spirits",
        "kuenz",
        "franziska",
        "graton",
        "ironbridge",
        "j. rieger",
        "steigmiller",
        "sasse",
        "sächsische",
        "san diego",
        "haus hettig",
        "savage & cooke",
        "slane",
        "smugglers' notch",
        "st. kilian distillers",
        "taconic",
        "h.clark",
        "tevsjö",
        "lepelaar",
        "baumgartner",
        "tommyrotter",
        "the waters",
        "traverse city whiskey",
        "nearest green",
        "virgil kaine lowcountry",
        "g. miclo",
        "hafendestillerie",
        "einbach",
        "walsh whiskey",
        "zeitzer whisky manufactur",
        "aero whisky",
        "anglesey",
        "arbikie",
        "bakery hill",
        "baltimore",
        "ko",
        "wilhelm behr",
        "hardenberg",
        "black bridge",
        "jeptha creed",
        "bluegrass",
        "turin",
        "preuschens",
        "bows",
        "brother justus",
        "wharf",
        "chicken cock",
        "churfirsten",
        "cley",
        "coppersea",
        "obst dirk böckenhoff",
        "detroit city",
        "distillery 291",
        "krauss",
        "east london",
        "scheibel mühle",
        "eschenbräu",
        "farny",
        "great northern distillery",
        "forgan distillery",
        "alex clark",
        "waldhorn klotz gbr",
        "franken bräu",
        "guillon",
        "kaikyo",
        "devil's distillery",
        "biospiritsxyz",
        "kartveli",
        "joadja",
        "tōsh",
        "new liberty",
        "belmont farm",
        "krobār craft",
        "baker williams",
        "launceston",
        "franzlahof",
        "hubertus vallendar",
        "manly",
        "the wild alps",
        "kumesen",
        "myken",
        "nibelungengold",
        "ninkasi",
        "o.z. tyler",
        "odd society",
        "old line spirits",
        "gyokusendo shuzo",
        "penninger",
        "khoday india",
        "de graal",
        "schmalwieser",
        "zum lobmüller",
        "du vercors",
        "seven stills",
        "signal hill spirits",
        "eifel",
        "oxford artisan",
        "spring bay",
        "lohn keiser",
        "clydeside",
        "lübbehusen",
        "riverbourne",
        "top of the hill",
        "lexington",
        "trebitsch old town",
        "schäffler bräu",
        "two james",
        "ugelris",
        "mt. uncle",
        "spezialitäten weidhof",
        "weingut dotzauer",
        "westward",
        "pittsburgh",
        "wilderness trail",
        "bendt",
        "wolf & oak",
        "brandhaus 7",
        "czeglédi pálinkafőzde",
        "10th street",
        "adelaide hills",
        "niigata",
        "anno",
        "dr. clyde",
        "backwoods",
        "ballykeefe",
        "baronie",
        "böckenhoff",
        "bauhöfer",
        "blackmoon",
        "boplaas",
        "kötztinger",
        "burwood",
        "bus",
        "chief's son",
        "circumstance",
        "cirka",
        "leiper's fork",
        "cooper king",
        "corra linn",
        "bronckhorst",
        "killara",
        "dartmoor",
        "august dinsing",
        "safe house",
        "three boys farm",
        "drilling",
        "the shed",
        "dueling barrels",
        "bossche stokers",
        "egg",
        "farthofer",
        "feller",
        "turabauer maass",
        "fossey's",
        "ghost coast",
        "glen wyvis",
        "golden moon",
        "hanson of sonoma",
        "hierber",
        "holweger",
        "holyrood",
        "sas distilleries",
        "irten'ge",
        "jobst",
        "weinhaus kilian",
        "killowen",
        "knaplund",
        "loburger brennereimanufaktur",
        "lagg",
        "last straw",
        "five points",
        "lonerider spirits",
        "the black bottle",
        "d'hautefeuille",
        "luca mariano",
        "zámecká palìrna blatná",
        "pianta brand",
        "greenbrier",
        "spirits workshop",
        "nonesuch",
        "nordmarkens",
        "otter craft",
        "philadelphia",
        "r.m. rose",
        "rochfort",
        "rose valley feinbrand",
        "long island spirits",
        "santan",
        "sagamore spirit",
        "kindschi söhne ag",
        "newport",
        "short mountain",
        "sin gold",
        "de paris",
        "ouche nanon",
        "santamanía",
        "skånska",
        "st. urban",
        "connacht",
        "lambicool",
        "still austin",
        "tahwahkaro",
        "moe",
        "tarnished truth",
        "iron house",
        "borders",
        "think destillers",
        "northmaen",
        "vareler brauhaus",
        "de laguiole",
        "ulex schnäpse",
        "pittermanns",
        "van brunt stillhouse",
        "vattudalen",
        "goudoulin",
        "vulkan brauerei",
        "hack",
        "waldkircher",
        "weyermann destillerie",
        "white peak",
        "yack creek",
        "yerushalmi",
        "5nines",
        "7k",
        "bodega abasolo",
        "brain brew",
        "backwoods craft spirits",
        "zweistein",
        "bergslagens",
        "republic restoratives",
        "broken bones",
        "brugse",
        "cathead",
        "distillerie charlier",
        "clara hof",
        "copenhagen",
        "copper rebublic",
        "craft works",
        "windecker dorfbrennerei",
        "devils river",
        "gasthof dinkel",
        "einar's",
        "lippert",
        "halber mond",
        "frey ranch",
        "furneaux",
        "headlands",
        "henstone",
        "tamar valley",
        "ocean king",
        "isarnhoe",
        "puchas",
        "la roche aux fées",
        "starlaw",
        "lawrenny",
        "loch brewery",
        "lost republic",
        "ludlow",
        "mammoth",
        "old carrick mill",
        "mb roland",
        "mourne dew",
        "ohishi",
        "j.w. kelly",
        "erongo mountain",
        "orma",
        "osuzuyama",
        "ragged branch",
        "dobson's",
        "castle & key",
        "rieger",
        "rogue spirits",
        "stapf",
        "eckerts",
        "feuergraben",
        "sall whisky",
        "alexander biselli",
        "didier barbe",
        "hard truth",
        "weinkellerei spielmann",
        "spirit works",
        "stammheimer",
        "adams",
        "vara",
        "aisling",
        "derwent",
        "creag dearg",
        "thornæs destilleri",
        "union horse",
        "uppsala destilleri",
        "mühlenbrennerei",
        "claeyssens de wambrechies",
        "watershed",
        "whiskey acres",
        "wild river mountain",
        "venakki",
        "wyndberg",
        "yserrain",
        "aber falls",
        "agitator",
        "t.o.s",
        "maison daucourt",
        "drumlin",
        "wild brennerei",
        "vienna craft",
        "inchdairnie",
        "diwisa willisau sa",
        "hawkshead",
        "american freedom",
        "klosterdistille machern",
        "mühlhäuser",
        "lautergold",
        "chateau du breuil",
        "moon distilling",
        "mwórveld b.v.",
        "top shelf international",
        "die kleine",
        "sakurao",
        "sons of vancouver",
        "evan william",
        "tria prima",
        "mccormick",
        "stock",
        "canadian mist",
        "hoffman",
        "old crow",
        "old comber",
        "frankfort",
        "ferintosh",
        "kellerstrass",
        "green river",
        "mellwood",
        "burke's",
        "parkmore",
        "glenfyne",
        "o.f.c. stagg",
        "thomas street george roe",
        "stromness",
        "black velvet",
        "gooderham",
        "southern distilleries",
        "corio",
        "continental distillers",
        "1000 hills",
        "10th mountain",
        "12.05",
        "1769",
        "18th street",
        "2bar",
        "3 badge",
        "3 howls",
        "45th parallel",
        "52eighty",
        "66 gilead",
        "acre",
        "adirondack",
        "aioi unibio",
        "alaska",
        "albany",
        "alchemy",
        "all points west",
        "allgäu",
        "alte",
        "altore",
        "american fifth",
        "andalusia",
        "appalachian",
        "applewood",
        "arbutus",
        "arcola",
        "arizona high spirits",
        "artist in residence",
        "ascendant",
        "astidama",
        "auchnagie",
        "axe and the oak",
        "az granata",
        "bachgau",
        "bad dog",
        "bainbridge",
        "bandon",
        "bankhall",
        "baoilleach",
        "barrel house",
        "basilico",
        "basque moonshiners",
        "batch 206",
        "bay area",
        "bear wallow",
        "belle isle",
        "belmont",
        "benachie",
        "bennnnndistillery",
        "bent",
        "bergwelt",
        "berkshire mountain",
        "betz",
        "bflo",
        "bières michard",
        "biolandhof köhler",
        "black bear",
        "black canyon",
        "black draft",
        "black heron",
        "black's",
        "blackfish",
        "blinking owl",
        "blue monkey",
        "blue ridge",
        "blue sky",
        "blue spirits",
        "boann",
        "böckl",
        "bogner",
        "bolanachi",
        "bone spirits",
        "boone county jail",
        "böttchehof",
        "bouck brothers",
        "branger",
        "bayer",
        "bühler",
        "brasch",
        "friz",
        "hübner",
        "kramer",
        "lettner",
        "ludwig faber",
        "roman kraus",
        "roßmann",
        "falckenthal",
        "chicago",
        "collier and mckeel",
        "colorado gold",
        "copper run",
        "crooked water",
        "cutler's",
        "dachstein destillerie mandlberggut",
        "dalaruan",
        "dallas distilleries",
        "dambachler",
        "dancing goat",
        "dancing pines",
        "dark corner",
        "dark horse",
        "death's door",
        "deception",
        "dehner",
        "denning's point",
        "ayutla",
        "limtuaco",
        "aldea",
        "siegfried herzog",
        "gößwein",
        "hirtner",
        "parzmair",
        "destylarnia piasecki",
        "devine spirits",
        "die klein rackelmann",
        "cherry rocher",
        "de la quintessence",
        "des bughes",
        "dreum",
        "du castor",
        "du pays d'othe",
        "du périgord",
        "du risoux",
        "du st. laurent",
        "janot",
        "theo preiss",
        "krucefix",
        "dixon’s distilled spirits",
        "do good",
        "doc porter's",
        "dogfish head",
        "domaine de bourjac",
        "don michael",
        "don quixote",
        "door county",
        "downslope",
        "doz de dauzanges",
        "driftless glen",
        "dry county",
        "dundashill",
        "durango",
        "dyrehøj vingård",
        "eastside",
        "echlinville",
        "gierer",
        "egilse",
        "eleven wells",
        "elkins",
        "ellensburg",
        "emperador",
        "erismann",
        "ezra cox",
        "fallstein",
        "familie franz lauritsch",
        "fifth state",
        "fisselier",
        "five & 20",
        "flag hill",
        "flat rock spirits",
        "florida caribbean",
        "florida farm",
        "fogs's end",
        "foothills",
        "franklin county",
        "franz stettner & sohn",
        "freeland spirits",
        "frongoch",
        "fugitives spirits",
        "geistreich",
        "gelephu",
        "georgia distilling",
        "ginebra san miguel",
        "glacier",
        "glenfoyle",
        "glenns creek",
        "goalong liquor",
        "godet",
        "golden distillery",
        "goodridge",
        "gourmet berner",
        "grand traverse",
        "grandten",
        "granit",
        "great northern",
        "great outback",
        "great wagon road",
        "greenbar",
        "griffin ranch",
        "grumsiner",
        "grüner baum",
        "gulf coast",
        "gutshof andres",
        "hali'imaile",
        "hartfield",
        "hartges",
        "headframe",
        "hiebl",
        "high wire",
        "highspire whiskey",
        "hinrichsen's",
        "höllberg",
        "holy",
        "homberg",
        "hood river",
        "hotel tango",
        "hounds tooth",
        "immortal spirits",
        "ingendael",
        "iron smoke",
        "iron wolf",
        "isaiah morgan",
        "isanti",
        "5 artisan",
        "ivy mountain",
        "j. carver",
        "j. riley",
        "jersey spirits",
        "jf strothman",
        "joe morgan's black diamond",
        "john emerald",
        "jonasberg stokerij",
        "josiah thedford",
        "kaerilis",
        "kentucky artisan",
        "kern & schweigert",
        "kgb spirits",
        "kinsip",
        "klein fitzke",
        "kleinhenz",
        "kloster zinna",
        "ko'olau",
        "koenig",
        "kohler hofladen",
        "kord",
        "kozuba",
        "la alazana",
        "lagler",
        "lamas",
        "lava bräu braumanufaktur",
        "lechtaler haussegen",
        "lee spirits",
        "leopold bros",
        "likörfabrik mikolasch",
        "litchfield",
        "lo artisan",
        "lochhead",
        "london distillers",
        "los 2 compadres",
        "lost state",
        "louâpre",
        "lynchburg",
        "lyon",
        "maiden derry",
        "maison du vigneron",
        "maison sivo",
        "malahats",
        "malibreiz",
        "malt mill",
        "manifest",
        "maraska",
        "marillenhof",
        "martes santo",
        "matter spirits",
        "mcclintock",
        "meiers allgäuer",
        "michelehof",
        "micil",
        "middle west",
        "mile high",
        "minhas",
        "minsk grape wines factory",
        "miscellaneous",
        "monkey hollow",
        "mont saint jean",
        "morris of rutherglen",
        "mosterei",
        "mountain state",
        "murree brewery",
        "myer farm",
        "mystic farm",
        "nahmias et fils",
        "new deal",
        "new england",
        "noble elite",
        "nordlicht",
        "north shore",
        "nun's island",
        "o'begley",
        "obst",
        "off the clock",
        "old dominick",
        "old elk",
        "old forge",
        "old school",
        "old sugar",
        "old tahoe",
        "ole smoky",
        "oola",
        "oppidan",
        "orange county",
        "orcas island",
        "ozark",
        "palìrna u zeleného stromu",
        "palmetto",
        "panther",
        "parliament",
        "peach street",
        "penderyn",
        "peterseil",
        "piedmont",
        "pierde almas",
        "pocketful of stones",
        "port chilkoot",
        "primushäusl",
        "prince edward",
        "gols",
        "prohibition distillery",
        "proof artisan distillers",
        "ransom",
        "re:find",
        "red bordner",
        "red bull",
        "red eagle",
        "reece's",
        "restless spirits",
        "rich grain",
        "robert meisner",
        "rockfilter",
        "royal brewhouse",
        "royal oak",
        "ryan & wood",
        "saint james spirits",
        "salm bräu",
        "sammerhof",
        "san diego sunshine",
        "santa fe spirits",
        "schloss marienburg",
        "schlossbrauerei autenried",
        "seacrets",
        "seattle",
        "second chance spirits",
        "seppelbauer",
        "seven brothers",
        "seven three",
        "shelter",
        "shirakawa",
        "shot in the dark craft",
        "sibling",
        "sierra norte",
        "sikkim",
        "silk city",
        "silver trail",
        "sinnesfreuden neber hagemann",
        "six & twenty",
        "skaalvenn",
        "skip rock distillers",
        "sliabh liag",
        "snitching lady",
        "sonoma brothers",
        "southern artisan spirits",
        "southern company",
        "southern tier",
        "souwester spirits",
        "spessarthof",
        "spezialitäten assulzerhof",
        "spirit of york",
        "spirits of french lick",
        "split rock",
        "springbrook hollow farm",
        "square one",
        "st. petersburg",
        "stadler",
        "standard wormwood",
        "starkenberg",
        "stilltheone",
        "stillwater spirits",
        "stratheden",
        "studio",
        "sugarlands",
        "sweet potato spirits",
        "swhisky",
        "swift",
        "syntax spirits",
        "tahoe moonshine",
        "tanduay distillers",
        "tatoosh",
        "tattersall",
        "tawny corn",
        "tekel",
        "temperance",
        "the block",
        "the cooper spirits",
        "the family jones",
        "the liberty",
        "mclaren vale",
        "mighty oak",
        "original texas legend",
        "splinter group",
        "village brewer",
        "thistle finch",
        "thomas wilhelm",
        "thumb butte",
        "thunder road",
        "tiger juice",
        "tirado",
        "tirril brewery",
        "tobias schmid",
        "top shelf distillers",
        "tovuz",
        "towcester mill brewery",
        "trail town still",
        "treecraft",
        "twenty third street",
        "twin creeks",
        "twin stills moonshine",
        "two doves",
        "union maltwhisky do brasil",
        "urban distilleries",
        "valentine",
        "vapor",
        "venus spirits",
        "viktor senn",
        "vinn",
        "virginia sweetwater",
        "vitis industries",
        "waldbrand destillerie",
        "wallner",
        "wayne gretzky estate",
        "weidmann & groh",
        "weinbau zur krone",
        "wein und likörfabrik h. a. wagner",
        "west virginia",
        "western reserve",
        "western son",
        "weutz",
        "wheat state",
        "whitmeyer's",
        "wibblers",
        "wijnhuis texel",
        "willie's",
        "winter park",
        "wishkah river",
        "wondertucky",
        "woody creek",
        "wood’s high mountain",
        "wylie howell",
        "yahara bay",
        "yalaha bootlegging",
        "zauser",
        "zöchmeister",
        "zogg mosterei",
        "æppeltreow",
        "suerlaenner",
        "volker theurer im gasthof lamm",
        "brickway",
        "broadbent",
        "broger",
        "bulleit",
        "bully boy",
        "caiseal",
        "cadushy",
        "carbon glacier",
        "cedar ridge",
        "central standard",
        "chzzzzz",
        "chambers bay",
        "steinlein",
        "roder",
        "remy martin",
        "hennessy",
        "pennco",
        "Camus",
        "medley",
        "George T. Stagg",
        "courvoisier",
        "bardstown",
        "louis royer",
        "booker noe",
        "shinshu",
        "miltonduff",
        "bernheim",
        "martell",
        "shinzato",
        "old grand-dad",
        "kyoto",
        "tasmania",
        "charpentier",
        "old taylor castle",
        "pasquet",
        "gwalia",
        "seagram",
        "tanqueray",
        "meukow",
        "osumi",
        "small concern",
        "seagram",
        "myagikyo",
        "port ellen",
        "arran",
        "lochindaal",
        "glen avon",
        "mortlach",
        "craigellachie",
        "highland park",
        "dufft own",
        "glentauchers",
        "yamazaki",
        "drumguish",
        "banff",
        "knockando",
        "1770",
        "girvan",
        "port charlotte",
        "glenlivet",
        "dumbarton",
        "longmorn",
        "bladnoch",
        "north port",
        "tweeddale",
        "macleod",
        "berheim",
        "averna",
        "brignac",
        "augier",
        "aurum",
        "benedictine",
        "ballor",
        "barbieri",
        "bardinet",
        "baron de ley",
        "trichard",
        "ballyvolane",
        "bacardi",
        "billecart",
        "black&",
        "bodvin",
        "castellana",
        "benvenuti",
        "craigduff",
        "ancient age",
        "asahikawa",
        "grants",
        "bermudez",
        "michel couvreur",
        "black forest",
        "amaro",
        "morton",
        "alize",
        "ambassador",
        "ambleville",
        "armore",
        "asbach",
        "atherton",
        "azabu",
        "bandeira",
        "bangyikhan",
        "barbancourt",
        "american distilling",
        "bardowie",
        "barnett",
        "casterac",
        "lustrac",
        "fauste",
        "sigognac",
        "barros",
        "armagnac",
        "flinders",
        "beefeater",
        "beenleigh",
        "beniotome",
        "beninnes",
        "bergslagens",
        "bersano",
        "bertolo",
        "bielle",
        "bisquit",
        "ashbrook",
        "black rock",
        "bomberger's",
        "berentzen",
        "borsci",
        "haig club",
        "dunglass",
        "ballechin",
        "belvedere",
        "chivas",
        "glencraig",
        "bansei",
        "inchmurrin",
        "beltane",
        "rhosdhu",
        "otard",
        "bonnie bros",
        "big hill",
        "stewards",
        "octomore",
        "black bull",
        "ben bracken",
        "ballantine"
    ]

    # Request
    data = request.get_json()

    # Body
    input = data.get('input', '')
    forbidden_words = data.get('forbidden_words', '')
    forbidden_distilleries = data.get('forbidden_distilleries', '')
    cutoff_input = data.get('cutoff', '')

    if(cutoff_input != ''):
        cutoff = cutoff_input

    # forbidden words filtering
    forbidden_words_default.extend(forbidden_words)
    for w in forbidden_words_default:
        input = input.replace(w, '')

    # logic
    splitted_input = input.split(" ")
    splitted_input = filter(lambda x: len(x) >= word_size, splitted_input)

    output = []
    for word in splitted_input:
        currentResult = difflib.get_close_matches(
            word, search_field, cutoff=cutoff)
        for i in currentResult:
            output.append(i)

    output = list(set(output))

    # forbidden distilleries filtering
    forbidden_distilleries_defaults.extend(forbidden_distilleries)
    for word in forbidden_distilleries_defaults:
        if word in output:
            output.remove(word)

    return jsonify(output)


if __name__ == "__main__":
    app.run(host='0.0.0.0', port=5000)
