import difflib


def run_autocorrect(input, forbidden_words, forbidden_distilleries, cutoff_input):
    forbidden_words_default = []
    forbidden_distilleries_defaults = []
    word_size = 6
    cutoff = 0.75
    search_field = [
        "aberlour",
        "kavalan",
        "glen garioch",
        "michter",
        "glen grant",
        "royal lochnagar",
        "Big Peat",
        "ardgowan",
        "blair athol",
        "jim beam",
        "hazelburn",
        "longrow",
        "glen elgin",
        "compass box",
        "haig's",
        "buchanan's",
        "bell's",
        "ardnahoe",
        "ben wyvis",
        "breuckelen",
        "four roses",
        "bivrost",
        "north british",
        "kanosuke",
        "cardrona",
        "lindores abbey",
        "finlaggan",
        "gerston & auchnagie",
        "strathearn",
        "kaiyo",
        "annandale",
        "macallan",
        "hibiki suntory",
        "willett",
        "dalmore",
        "mars shinshu",
        "lagavulin",
        "fettercairn",
        "talisker",
        "bow mor",
        "beam suntory",
        "nikka",
        "benromach",
        "wild turkey",
        "ardbeg",
        "teaninich",
        "glonfarcias",
        "carsebridge",
        "glenfiddich",
        "convalmore",
        "glenmorangie",
        "midleton",
        "laphroaig",
        "linkwood",
        "rosebank",
        "naturally rich",
        "strathisla",
        "bimber",
        "beriach",
        "amrut",
        "glendronach",
        "bunnahabhain",
        "whyte & mackay",
        "bruichladdich",
        "heaven hill",
        "glenrothes",
        "high west",
        "nevada h&c",
        "hillside",
        "coleburn",
        "shizuoka",
        "old pulteney",
        "old forester",
        "glen mhor",
        "jameson",
        "kilkerran",
        "knockdhu",
        "daftmill",
        "dalwhinnie",
        "balvenie",
        "caol ila",
        "littlemill",
        "inchgower",
        "caledonian",
        "dallas dhu",
        "glen keith",
        "caperdonich",
        "mosstowie",
        "imperial",
        "garrison brothers",
        "sullivans cove",
        "teeling",
        "glen albyn",
        "tomintoul",
        "pittyvaich",
        "kentucky owl",
        "inverleven",
        "strathclyde",
        "garnheath",
        "ardnamurchan",
        "tamdhu",
        "balblair",
        "scapa",
        "north of scotland",
        "cragganmore",
        "jack daniels",
        "tomatin",
        "suntory whisky",
        "raasay",
        "dailuaine",
        "glenglassaugh",
        "port dundas",
        "lochside",
        "wolfburn",
        "glenlossie",
        "chita",
        "bushmills",
        "invergordon",
        "tormore",
        "clynelish",
        "glenallachie",
        "brown forman",
        "ambler",
        "glen scotia",
        "yamazakura",
        "orphan barrel",
        "barrell craft",
        "royal brackla",
        "edradour",
        "limestone branch",
        "ledaig",
        "tamnavulin",
        "cambus",
        "glenkinchie",
        "glen spey",
        "deanston",
        "ben nevis",
        "glengoyne",
        "torabhaig",
        "glen moray",
        "kilchoman",
        "glenturret",
        "speyburn",
        "glencadam",
        "kininvie",
        "benrinnes",
        "waterford",
        "whistlepig",
        "westland",
        "balcones",
        "nelsons green brier",
        "cardhu",
        "mclain kyne",
        "balmenach",
        "lakes",
        "penderyn",
        "jura",
        "cutwater",
        "akkeshi",
        "oban",
        "nc'nean",
        "tullamore",
        "barton 1792",
        "eden mill",
        "kingsbarns",
        "auchroisk",
        "braeval",
        "auchentoshan",
        "grants",
        "tuthilltown spirits",
        "mannochmore",
        "tullibardine",
        "copper rivet",
        "aberfeldy",
        "stronachie",
        "glenburgie",
        "white horse123",
        "kawasaki",
        "glendullan",
        "lux row",
        "aultmore",
        "new riff",
        "glenury",
        "magdalene",
        "millburn",
        "antiquary",
        "bardstown",
        "old carter",
        "macduff",
        "one eight",
        "western spirits",
        "boone",
        "cotswolds",
        "louisville",
        "jos a magnus",
        "proof wood ventures",
        "st augustine",
        "maker's mark",
        "strathmill",
        "ardmore",
        "bourbon 30",
        "filibuster",
        "smith bowman",
        "backbone",
        "glen flagler",
        "dalmunach",
        "woodford reserve",
        "finger lakes",
        "hiram walker",
        "high coast",
        "kinclaith",
        "glenlochy",
        "stitzel",
        "dornoch",
        "glenugie",
        "glencraig",
        "ailsa bay",
        "breckenridge",
        "schenley",
        "starward new world",
        "dads hat",
        "catskill",
        "cutty sark",
        "ranger creek",
        "boston harbor",
        "fremont mischief",
        "glenmore",
        "ladyburn",
        "crown royal",
        "cooley",
        "allt a bhainne",
        "prichards",
        "buffalo trace",
        "tobermory",
        "killyloch",
        "james e. pepper",
        "willowbank",
        "brora",
        "gasthof hirsch",
        "loch ewe",
        "abhainn dearg",
        "widow jane",
        "reservoir distillery",
        "blaum",
        "cleveland",
        "chattanooga",
        "arbikie",
        "coppersea",
        "three boys farm",
        "glen wyvis",
        "holyrood",
        "lagg",
        "borders",
        "inchdairnie",
        "american freedom",
        "ferintosh",
        "parkmore",
        "glenfyne",
        "bainbridge",
        "blue ridge",
        "glenfoyle",
        "bulleit",
        "miltonduff",
        "croftengea",
        "inchfad",
        "rhosdhu",
        "port ellen",
        "arran",
        "lochindaal",
        "glen avon",
        "mortlach",
        "craigellachie",
        "highland park",
        "dufft own",
        "glentauchers",
        "drumguish",
        "banff",
        "knockando",
        "1770",
        "girvan",
        "port charlotte",
        "dumbarton",
        "lagmern",
        "bladnoch",
        "north port",
        "springbank",
        "glenlivet",
        "loch lomond",
        "craigduff",
        "armore",
        "bardowie",
        "beninnes",
        "haig club",
        "dunglass",
        "ballechin",
        "glencraig",
        "octomore",
        "black bull",
        "ben bracken"
    ]

    if(cutoff_input != ''):
        cutoff = cutoff_input

    forbidden_words_default.extend(forbidden_words)
    for w in forbidden_words_default:
        input = input.replace(w, '')

    splitted_input = input.split(" ")
    splitted_input = filter(lambda x: len(x) >= word_size, splitted_input)

    output = []
    for word in splitted_input:
        currentResult = difflib.get_close_matches(
            word, search_field, cutoff=cutoff)
        for i in currentResult:
            output.append(i)

    output = list(set(output))
    forbidden_distilleries_defaults.extend(forbidden_distilleries)
    for word in forbidden_distilleries_defaults:
        if word in output:
            output.remove(word)

    return output
